### PR TITLE
Create newDB.csv

### PR DESCRIPTION
**Pull request by mr-robot77**
1. add new database with 25500 names 
2. see difference between old main database 19000 and new database with 25500 names

### CODE REVIEW

**Comment by zeoses** [comment]
hi
I checked the dataset I think this dataset has a low level of accuracy because many names have the wrong gender(you can see it in the picture). 
Screenshot from 2023-06-21 11-05-45

**Comment by mr-robot77** [comment]
Hi. Yes it does because it is from a ML project
So it doesn't fit your project or if you want to use it, you should fix the wrong column. For example, if you want to use this dataset, you can use a data analytics tool to prepare this data correctly for your project.

**Comment by zeoses** [comment]
thanks, I think it doesn't benefit spending a lot of time on this dataset, because Im trying to add a new feature, for names used for both genders, which I think spending time for this is better than I change the dataset.
if you can change the database a improve it, without any conflict with this dataset, I welcome it.

**Comment by mr-robot77** [comment]
So we move on from it
I think it better should be that you mention in README details about what features you want and adding todo list with checkmarks button till others can help you

**Comment by zeoses** [comment]
that's a great idea, I will add this part to Readme.
thank you for your suggestion.
if have you a new idea or suggestion, say me add it.

**Pull request closed without merging**
